### ISSUE TITLE
Next page button not working

### ISSUE THREAD

**Issue by franco15** [fontIconPicker/react-fonticonpicker#12]
When i click the button to switch to another page with the other icons, it just does nothing and its not switching pages. Any idea why?

**Comment by ApacheEx** [comment]
+1 I have the same issue. It can be reproduced when `showCategory={false}` or `showSearch={false}`

it looks like the issue here in this code: https://github.com/fontIconPicker/react-fonticonpicker/blob/master/src/js/components/FontIconPicker.jsx#L110
