### ISSUE TITLE
Use FontIconPicker with FontAwesome 4.7

### ISSUE THREAD

**Issue by davidgolden** [fontIconPicker/react-fonticonpicker#3]
Hey @swashata, thanks for this sweet icon picker! I'm needing to use the older version of FontAwesome and it doesn't seem to be working with FontIconPicker. All I've done so far is change the CDN to the legacy version. What configurations would you change on FIP so that 4.7 will work?

**Comment by swashata** [comment]
Hi, thanks for your good words. About FontAwesome 4, you just need to change the `icons` prop.

```jsx
<FontIconPicker icons={['fa fa-address-book', 'fa fa-bar-chart']} />
```

I hope I am clear.

**Comment by davidgolden** [comment]
Ah, stupid mistake- had my head in some other code that needed to omit the 'fa' part. Sorry and thank you!

**Comment by mikeover** [comment]
AFAICT, this doesn't work quite right as the drop down icon for opening the selector uses icons not in FA 4.7. Here's what I'm seeing:

<img width="153" alt="screen shot 2018-11-10 at 9 45 39 am" src="https://user-images.githubusercontent.com/5045642/48302677-765c7700-e4cd-11e8-8a3d-6624cf4b66b0.png">
