### ISSUE TITLE
Close Picker on Select

### ISSUE THREAD

**Issue by davidgolden** [fontIconPicker/react-fonticonpicker#5]
I'm not seeing a built in function to close the icon picker when an icon is selected. Does this already exist somewhere in the component?

**Comment by swashata** [comment]
Hi, we actually don't have it yet, but I would definitely love a PR for this. It is already there 

https://github.com/fontIconPicker/react-fonticonpicker/blob/230de9e02af17c32829fc9dcaca24703d8a64524/src/js/components/FontIconPicker.jsx#L247 

I don't know why we don't have this as a feature in props ☹️

**Comment by davidgolden** [comment]
Great, I will work on it!
